### ISSUE TITLE
Possible to customize slug creation logic?

### ISSUE THREAD

**Issue by vfonic** [neighborland/sluggi#13]
Thanks for the great gem!

I'm just exploring the API and looking for ways to customize slug generation/creation algorithm.

I already have an app with slugs and I'd like to switch it to sluggi.

I'd like all the old slugs to stay the same.

Where should I look or what's the easiest way to change how slugs are being created?

Thank you!

**Comment by vfonic** [comment]
It looks like both `#slug_value` and `#slug_candidates` will at the end call `#clean_slug`, which calls `#parameterize` on the given string, which breaks my slugging algorithm.
https://github.com/neighborland/sluggi/blob/384ca78aeda08fdb0b89f83467f060f781dad486/lib/sluggi/model.rb#L33

I'm using case-sensitive slugs and parameterize downcases the slug. :(

Is there any way to avoid this?

I'd also love to use `#slug_candidates` in case of conflicting slugs. I think `#clean_slug` is a single point of transforming passed-in value to a slug. If it would allow to accept custom slugging algorithm, it might work.

```rb
# used to be #clean_slug
# override this method to use you own logic for converting slug candidates to slugs
def convert_to_slug(value)
  value&.parameterize
end
```

What do you think?

**Comment by teeparham** [comment]
It sounds like you could override `#clean_slug` to call a case-sensitive `#parameterize`-like method.

`#parameterize` is defined by ActiveSupport:

https://github.com/rails/rails/blob/master/activesupport/lib/active_support/inflector/transliterate.rb#L92

**Comment by vfonic** [comment]
That's what I was thinking. I'll just do that. 👍 

Thank you!
